Redesigning Students Page
Carleton-Blueprint/carleton-blueprint.github.io pull request #37
Opened 2024-06-14 15:01 UTC by jzbouri

2024-07-16 06:25 UTC, heyitsOK requested changes
please add in the design changes that hendry has made on figma as well.
thanks for all your hard work!!!

2024-07-16 06:25 UTC, heyitsOK commented on src/app/(pages)/home/_components/BlockContainer.tsx
please change the flip conditional css on line 27 to be a ternary operator
```${flip === true ? "bg-blueprint-50" : "bg-white"}```

2024-07-18 17:44 UTC, jzbouri commented on src/app/(pages)/students/page.tsx
> +    <div className="bg-blueprint-100 min-h-screen overflow-x-hidden">
Not sure why but when I change the bg to blueprint-50, it just shows up as white. Might be an issue with running it in dev, can't find any other reason for it not working
<img width="1291" alt="Screenshot 2024-07-18 at 1 43 06 PM" src="https://github.com/user-attachments/assets/72e5ed82-8a7d-4682-9636-cfd58415527d">

2024-07-18 17:48 UTC, jzbouri commented on src/app/(pages)/students/_components/Section.tsx
> +        <BlockContainer title={team.teamName + " Team -"} roundedCorners={true} flip shadow={true}>
would you like me to make those changes to BlockContainer.tsx?

2024-07-28 19:35 UTC, heyitsOK approved these changes
looks very good and everything is responsive.
thank you jalal!

2024-07-28 19:36 UTC, merged